defaults: &defaults
  address: localhost
  port: 5001
  raftId: pi1
  raftDir: data
  raftBootstrap: false
  life: 100
  players:
    - pi1
    - pi2
    - pi3
    - pi4
  addressPool:
    - 192.168.8.160:5001
    - 192.168.8.167:5001
    - 192.168.8.103:5001
    - 192.168.8.151:5001

<<: *defaults
# uncomment to overwrite defaults
# address:
# port:
raftId: pi2
# raftDir:
# raftBootstrap:
# life:
# players:
